"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import React from 'react';
// import {MyContext} from './api/auth/contexts/myContext';
// import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
// import InactivityTracker from './components/InactivityTracker';

export default function RootLayout(
    // <>
    //   <InactivityTracker onLogout={handleLogout} />
    //   <Component {...pageProps} />
    // </>
  {
  children,
}: {
  children: React.ReactNode
}) {
  return (
        <html lang="en">
          <head>
            <script src="https://www.google.com/recaptcha/enterprise.js?render=6LcaqkApAAAAAGadmPPxtME3R4lLUGqjKI6v_yzP"/>
          </head>
          <body className={inter.className}>
              {/* <InactivityTracker onLogout={handleLogout} /> */}
              {children}
          </body>
        </html>
  )
}